version: '2'
services:
    monolitic-app:
        image: monolitic
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://monolitic-mysql:3306/monolitic?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    monolitic-mysql:
        extends:
            file: mysql.yml
            service: monolitic-mysql
